cache: cache
logging:
  enabled: true
  level: DEBUG
dscan:
  bg_color: [25, 25, 25]
  enabled: true
  font_scale: 0.5
  font_thickness: 1
  hotkey_transparency: alt+shift+f
  hotkey_mode: alt+shift+m
  stats_provider: zkill
  rate_limit_retry_delay: 5
  aggregated_mode_threshold: 50
  ignore: []
  timeout: 10
  diff_timeout: 60
  group_rect_width: 3
  transparency: 180
  transparency_color: [64, 64, 64]
  transparency_on: true
  hover_color: [80, 80, 255] 
  groups:
    blue:
      entities: [The Initiative.]
      color: [255, 206, 135]
    red:
      entities: [Fraternity.]
      color: [0, 0, 255]
      