cache: cache
api:
  enabled: false
  host: 127.0.0.1
  port: 8721
logging:
  enabled: true
  level: INFO
dscan:
  font: C:/Windows/Fonts/arial.ttf
  bg_color: [45, 45, 145]
  enabled: true
  font_scale: 0.5
  font_thickness: 1
  hotkey_overlay: alt+shift+f
  hotkey_clickthrough: alt+shift+a
  hotkey_bg: alt+shift+s
  hotkey_mode: alt+shift+m
  stats_provider: zkill
  rate_limit_retry_delay: 5
  aggregated_mode_threshold: 50
  ignore: []
  timeout: 10
  diff_timeout: 60
  group_rect_width: 3
  transparency: 180
  transparency_color: [64, 64, 64]
  transparency_on: true
  hover_color: null
  groups:
    blue:
      entities: [The Initiative.]
      color: [255, 206, 135]
    red:
      entities: [Fraternity.]
      color: [0, 0, 255]
  pilot_colors:
    default_color: [255, 255, 255]
    rules:
      dangerous:
        color: [0, 0, 255]
        kills_min: 100
        danger_min: 70
      cautious:
        color: [0, 255, 255]
        kills_min: 10
        danger_min: 20
