logging:
  enabled: true
  level: INFO
dscan:
  bg_color: [25, 25, 25]
  enabled: true
  font_scale: 0.5
  font_thickness: 1
  hotkey_transparency: alt+shift+f
  hotkey_mode: alt+shift+m
  stats_provider: zkill
  rate_limit_retry_delay: 5
  aggregated_mode_threshold: 300
  ignore_alliances: []
  ignore_corps: []
  timeout: 10
  transparency: 180
  transparency_color: [64, 64, 64]
  transparency_on: true
