[project]
authors = ["cryonox <cryonox@gmail.com>"]
channels = ["conda-forge"]
name = "eve_overlay"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.13"
pip = ">=25.0.1,<26"

[pypi-dependencies]
pyinstaller = ">=6.15.0, <7"
pyyaml = ">=6.0.2, <7"
global-hotkeys = ">=0.1.7, <0.2"
tqdm = ">=4.67.1, <5"
typing-extensions = ">=4.0.0"
pyperclip = ">=1.9.0, <2"
opencv-contrib-python = ">=4.12.0.88, <5"
pywin32 = ">=311, <312"
rich = ">=14.1.0, <15"
aiohttp = ">=3.12.15, <4"
bidict = ">=0.23.1, <0.24"
requests = ">=2.32.5, <3"
marisa-trie = ">=1.3.1, <2"
leb128 = ">=1.0.8, <2"
matplotlib = ">=3.10.6, <4"
html2image = ">=2.0.7, <3"
pyqt5 = ">=5.15.11, <6"
patch = ">=1.16, <2"
loguru = ">=0.7.3, <0.8"
